// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, oauth_provider, oauth_id, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, email, oauth_provider, oauth_id, created_at, updated_at
`

type CreateOAuthUserParams struct {
	Email         string      `json:"email"`
	OauthProvider pgtype.Text `json:"oauth_provider"`
	OauthID       pgtype.Text `json:"oauth_id"`
}

type CreateOAuthUserRow struct {
	ID            int64            `json:"id"`
	Email         string           `json:"email"`
	OauthProvider pgtype.Text      `json:"oauth_provider"`
	OauthID       pgtype.Text      `json:"oauth_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (CreateOAuthUserRow, error) {
	row := q.db.QueryRow(ctx, createOAuthUser, arg.Email, arg.OauthProvider, arg.OauthID)
	var i CreateOAuthUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, email, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           int64            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuthProvider = `-- name: GetUserByOAuthProvider :one
SELECT id, email, password_hash, oauth_provider, oauth_id, created_at, updated_at
FROM users
WHERE oauth_provider = $1 AND oauth_id = $2
`

type GetUserByOAuthProviderParams struct {
	OauthProvider pgtype.Text `json:"oauth_provider"`
	OauthID       pgtype.Text `json:"oauth_id"`
}

type GetUserByOAuthProviderRow struct {
	ID            int64            `json:"id"`
	Email         string           `json:"email"`
	PasswordHash  pgtype.Text      `json:"password_hash"`
	OauthProvider pgtype.Text      `json:"oauth_provider"`
	OauthID       pgtype.Text      `json:"oauth_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByOAuthProvider(ctx context.Context, arg GetUserByOAuthProviderParams) (GetUserByOAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthProvider, arg.OauthProvider, arg.OauthID)
	var i GetUserByOAuthProviderRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
