// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int64            `json:"id"`
	Email         string           `json:"email"`
	PasswordHash  pgtype.Text      `json:"password_hash"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	OauthProvider pgtype.Text      `json:"oauth_provider"`
	OauthID       pgtype.Text      `json:"oauth_id"`
}
